CO2Cap: 0
CapacityReserveMargin: 0
EnergyShareRequirement: 1
LongDurationStorage: 0
MinCapReq: 0
ModelingToGenerateAlternatives: 0
ModelingtoGenerateAlternativeSlack: 0.1
NetworkExpansion: 0
OperationWrapping: 1
OverwriteResults: 0
ParameterScale: 0
PrintModel: 0
Reserves: 0
Solver: Cbc
StorageLosses: 0
TimeDomainReduction: 0
TimeDomainReductionFolder: TDR_Results
Trans_Loss_Segments: 1
UCommit: 0
WriteShadowPrices: 1
